# -*- coding: utf-8 -*-
"""LipNet_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P5ZHT4JGNMRID5jQbQOl5OOHFkVRfIKV
"""

import os
import glob
import cv2
import numpy as np
import zipfile
import gdown
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from transformers import pipeline

print("TensorFlow:", tf.__version__)

# Change the URL if you use your own dataset link
url = 'https://drive.google.com/uc?id=1YlvpDLix3S-U8fd-gqRwPcWXAXm8JwjL'
zip_out = "lipread_dataset.zip"
if not os.path.exists("dataset"):
    gdown.download(url, zip_out, quiet=False)
    with zipfile.ZipFile(zip_out, 'r') as z:
        z.extractall("dataset")
print("Dataset root folders (first 5):", os.listdir("dataset")[:5])

IMG_SIZE = (50, 100)   # (height, width)
MAX_FRAMES = 75        # fixed number of frames per video

def load_video_fixed(path, max_frames=MAX_FRAMES, img_size=IMG_SIZE):
    h, w = img_size
    frames = np.zeros((max_frames, h, w), dtype=np.float32)  # preallocated
    cap = cv2.VideoCapture(path)
    idx = 0
    while idx < max_frames:
        ret, frame = cap.read()
        if not ret:
            break
        if frame is None:
            break
        # convert to gray and resize (ensure consistent shape)
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        gray = cv2.resize(gray, (w, h))
        frames[idx] = gray.astype(np.float32) / 255.0
        idx += 1
    cap.release()
    # if fewer frames read, remainder stays zeros (padding)
    return frames  # shape (MAX_FRAMES, h, w)

def find_alignment_word(video_filename, align_folder):
    base = os.path.splitext(video_filename)[0]
    cand = os.path.join(align_folder, base + ".align")
    if os.path.exists(cand):
        with open(cand, "r", errors="ignore") as f:
            lines = [l.strip() for l in f.readlines() if l.strip()]
            # find the first non-silence word token (safe heuristic)
            words = []
            for L in lines:
                parts = L.split()
                if len(parts) >= 3:
                    token = parts[-1]
                    if token.lower() not in ("sil", "sp", "pause"):
                        words.append(token)
            if words:
                return words[-1]  # last spoken token in that alignment
    return None

def load_dataset_grid(root_base="dataset"):
    video_dir = os.path.join(root_base, "data", "s1")
    align_dir = os.path.join(root_base, "data", "alignments", "s1")
    X, y_text, y_emotion, names = [], [], [], []
    if not os.path.isdir(video_dir):
        raise FileNotFoundError(f"Video folder not found: {video_dir}")
    for fname in sorted(os.listdir(video_dir)):
        if not fname.lower().endswith((".mpg", ".mp4", ".avi")):
            continue
        path = os.path.join(video_dir, fname)
        # load fixed-size padded frames
        frames = load_video_fixed(path)
        # get word from align file if possible
        word = find_alignment_word(fname, align_dir)
        if word is None:
            # fallback: use first 6 chars of filename as pseudo-label
            word = os.path.splitext(fname)[0][:6]
        X.append(frames)
        y_text.append(word.lower())
        y_emotion.append("neutral")  # dataset doesn't contain emotion labels -> default
        names.append(fname)
    X = np.array(X, dtype=np.float32)  # shape (N, MAX_FRAMES, h, w)
    y_text = np.array(y_text)
    y_emotion = np.array(y_emotion)
    print(f"Loaded {len(X)} videos from {video_dir}")
    return X, y_text, y_emotion, names

X, y_text, y_emotion, names = load_dataset_grid("dataset")
print("Example file:", names[0], "label:", y_text[0])
print("X shape:", X.shape)

text_encoder = LabelEncoder()
y_text_enc = text_encoder.fit_transform(y_text)   # numeric labels for words

emotion_encoder = LabelEncoder()
y_emotion_enc = emotion_encoder.fit_transform(y_emotion)  # likely single class 'neutral'

X_train, X_test, y_text_train, y_text_test, y_emotion_train, y_emotion_test = train_test_split(
    X, y_text_enc, y_emotion_enc, test_size=0.15, random_state=42, stratify=y_text_enc
)

# expand channels dimension
X_train_np = np.expand_dims(X_train, -1).astype("float32")  # (N, frames, h, w, 1)
X_test_np = np.expand_dims(X_test, -1).astype("float32")

vocab_size = len(text_encoder.classes_)
num_emotions = max(1, len(emotion_encoder.classes_))

print("Train:", X_train_np.shape, "Test:", X_test_np.shape)
print("Vocab size (unique words):", vocab_size, "Emotion classes:", num_emotions)

from tensorflow.keras import Model

def build_stable_model(vocab_size, num_emotions, input_shape=(MAX_FRAMES, IMG_SIZE[0], IMG_SIZE[1], 1)):
    inp = layers.Input(shape=input_shape, name="video_input")
    x = layers.Conv3D(32, (3,3,3), activation='relu', padding='same')(inp)
    x = layers.MaxPool3D((1,2,2))(x)
    x = layers.BatchNormalization()(x)

    x = layers.Conv3D(64, (3,3,3), activation='relu', padding='same')(x)
    x = layers.MaxPool3D((1,2,2))(x)
    x = layers.BatchNormalization()(x)

    # collapse spatial dims per frame to make sequence features
    x = layers.TimeDistributed(layers.Flatten())(x)  # (batch, frames, features)
    x = layers.Bidirectional(layers.GRU(128, return_sequences=False))(x)  # final sequence vector

    # Word classification head
    word_out = layers.Dense(vocab_size, activation="softmax", name="word_output")(x)

    # Emotion head (softmax if multiple, else sigmoid)
    if num_emotions > 1:
        emotion_out = layers.Dense(num_emotions, activation="softmax", name="emotion_output")(x)
        loss_emotion = "sparse_categorical_crossentropy"
    else:
        # single class -> make it binary format (still use sigmoid)
        emotion_out = layers.Dense(1, activation="sigmoid", name="emotion_output")(x)
        loss_emotion = "binary_crossentropy"

    model = Model(inputs=inp, outputs=[word_out, emotion_out])
    model.compile(
        optimizer="adam",
        loss={"word_output": "sparse_categorical_crossentropy", "emotion_output": loss_emotion},
        metrics={"word_output": "accuracy", "emotion_output": "accuracy"}
    )
    return model

model = build_stable_model(vocab_size, num_emotions, input_shape=X_train_np.shape[1:])
model.summary()

# Train on small subset to avoid long runs; increase if you have GPU and time
train_count = min(200, X_train_np.shape[0])
X_tr = X_train_np[:train_count]
y_word_tr = y_text_train[:train_count]
y_emo_tr = y_emotion_train[:train_count]

history = model.fit(
    X_tr,
    {"word_output": y_word_tr, "emotion_output": y_emo_tr},
    validation_split=0.1,
    epochs=3,
    batch_size=8,
    verbose=2
)

import heapq
def beam_search_decoder(probs_seq, beam_width=3):
    # probs_seq: numpy array shape (T, V) — probabilities per time-step
    sequences = [([], 0.0)]
    for t in range(probs_seq.shape[0]):
        all_candidates = []
        for seq, score in sequences:
            for c in range(probs_seq.shape[1]):
                p = probs_seq[t, c]
                new_seq = seq + [c]
                new_score = score - np.log(p + 1e-12)
                all_candidates.append((new_seq, new_score))
        sequences = sorted(all_candidates, key=lambda tup: tup[1])[:beam_width]
    return sequences[0][0]

# pick a test sample
idx = 0
x_sample = X_test_np[idx:idx+1]  # shape (1, frames, h, w, 1)
true_word = text_encoder.inverse_transform([y_text_test[idx]])[0]
true_emotion = emotion_encoder.inverse_transform([y_emotion_test[idx]])[0] if num_emotions > 1 else emotion_encoder.inverse_transform([0])[0]

pred_word_probs, pred_emo = model.predict(x_sample, verbose=0)

# word prediction (direct classifier)
pred_word_idx = int(np.argmax(pred_word_probs[0]))
predicted_word = text_encoder.inverse_transform([pred_word_idx])[0]

# emotion: map prediction to label
if num_emotions > 1:
    pred_emo_idx = int(np.argmax(pred_emo[0]))
    predicted_emotion = emotion_encoder.inverse_transform([pred_emo_idx])[0]
else:
    # single class fallback
    predicted_emotion = emotion_encoder.inverse_transform([0])[0]

# Demonstrate beam search by creating a repeated prob sequence (demo purpose)
probs_seq = np.tile(pred_word_probs[0], (MAX_FRAMES, 1))  # shape (T, V)
decoded_seq = beam_search_decoder(probs_seq, beam_width=5)
# decoded_seq is a list of token indices per time-step; collapse to most frequent token:
most_common_idx = max(set(decoded_seq), key=decoded_seq.count)
beam_decoded_word = text_encoder.inverse_transform([most_common_idx])[0]

# text-based emotion classifier (transformer)
try:
    text_emotion_pipeline = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base", top_k=1)
    text_emotion_label = text_emotion_pipeline(predicted_word)[0]['label']
except Exception as e:
    text_emotion_label = "N/A"

print("====== Final Prediction Result ======")
print("Predicted Word (classifier) :", predicted_word)
print("Beam-decoded Word (demo)    :", beam_decoded_word)
print("True Word                   :", true_word)
print("Predicted Emotion (model)   :", predicted_emotion)
print("Text-based Emotion (pipe)   :", text_emotion_label)
print("True Emotion                :", true_emotion)

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
from google.colab import files

uploaded = files.upload()   # Upload a .mp4, .avi, or .mpg file
video_path = list(uploaded.keys())[0]
print(f"✅ Uploaded: {video_path}")

def load_video(path):
    cap = cv2.VideoCapture(path)
    frames = []

    while True:
        ret, frame = cap.read()
        if not ret:
            break
        # Convert to grayscale
        try:
            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        except:
            frame = np.mean(frame, axis=-1).astype(np.uint8)

        # Resize to (height=50, width=100)
        frame = cv2.resize(frame, (100, 50))
        frames.append(frame)

        # Stop once MAX_FRAMES reached
        if len(frames) >= MAX_FRAMES:
            break

    cap.release()

    # Pad short videos with black frames
    while len(frames) < MAX_FRAMES:
        frames.append(np.zeros((50, 100), dtype=np.uint8))

    # Convert list to numpy array and normalize
    frames = np.stack(frames, axis=0).astype("float32") / 255.0
    frames = np.expand_dims(frames, axis=-1)  # shape: (75, 50, 100, 1)
    return frames

test_video = load_video(video_path)
test_video = np.expand_dims(test_video, axis=0)
print("🎞 Video preprocessed successfully. Shape:", test_video.shape)

def beam_search_decoder(predictions, beam_width=5):
    import heapq
    predictions = np.atleast_2d(predictions)  # ensures shape (T, V)
    T, V = predictions.shape

    sequences = [([], 0.0)]  # (sequence, log-probability)
    for t in range(T):
        all_candidates = []
        row = predictions[t]
        for seq, score in sequences:
            for j, prob in enumerate(row):
                new_seq = seq + [j]
                new_score = score - np.log(prob + 1e-9)
                all_candidates.append((new_seq, new_score))
        sequences = heapq.nsmallest(beam_width, all_candidates, key=lambda x: x[1])
    return sequences[0][0]

preds_text, preds_emotion = model.predict(test_video)

# Beam search decoding for text
beam_indices = beam_search_decoder(preds_text[0])
decoded_word = ''.join([text_encoder.inverse_transform([i])[0] for i in beam_indices if i < len(text_encoder.classes_)])

# Emotion prediction
emotion_label = emotion_encoder.inverse_transform([np.argmax(preds_emotion[0])])

print("🗣 Predicted Word:", decoded_word)
print("😊 Predicted Emotion:", emotion_label[0])